image: Visual Studio 2022
artifacts:
  - path: '**\jsreport.Binary*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.Binary.sln
before_build:
  - cmd: dotnet restore
deploy:
  provider: NuGet
  api_key:
    secure: bAvzGZkRLdXslqjhneI/rdbYgOoDF8DY3q2ewaG/OKW0ze8lJEh2Jyv7XCv8JcWH
  on:
    appveyor_repo_tag: true
test_script:
- cd jsreport.Binary.Test
- dotnet test

