image: Visual Studio 2017
artifacts:
  - path: '**\jsreport.Binary*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.Binary.sln
before_build:
  - cmd: dotnet restore
deploy:
  provider: NuGet
  api_key:
    secure: 4fzGkFShqQOo4eE2dcjEWvp3FwHDVrZ9h4bvj2jeUNzKAC+jXNGtPOeBdgZFjpxR
  on:
    appveyor_repo_tag: true
test_script:
- cd jsreport.Binary.Test
- dotnet test

